[package]
name = "dotfilesctldev"
version = "0.1.0"
edition = "2024"

[dependencies]
home = "0.5.12"
libdotfilesctlcfg = { path = "../libdotfilesctlcfg" }
libdotfilesctldev = { path = "../libdotfilesctldev" }
