[package]
name = "libdotfilesctl"
version = "0.1.0"
edition = "2024"

[dependencies]
libdotfilesctlcfg = { path = "../libdotfilesctlcfg" }
leon = "3.0.2"
runas = "1.2.0"
which = "8.0.0"
whoami = "1.6.1"
os_info = "3.14.0"
dirs = "6.0.0"
console = "0.16.2"
